services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    ports:
      - "1379:7000"
    networks:
      - app-network

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DATABASE: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5913:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge